/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugPRouteImport } from './routes/$slug/p'
import { Route as AjudaIndexRouteImport } from './routes/ajuda.index'
import { Route as AjudaSlugRouteImport } from './routes/ajuda.$slug'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutCarrinhoRouteImport } from './routes/checkout/carrinho'
import { Route as CheckoutLoginRouteImport } from './routes/checkout/login'
import { Route as CheckoutPedidoRouteImport } from './routes/checkout/pedido'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugPRoute = SlugPRouteImport.update({
  id: '/$slug/p',
  path: '/$slug/p',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaIndexRoute = AjudaIndexRouteImport.update({
  id: '/ajuda/',
  path: '/ajuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaSlugRoute = AjudaSlugRouteImport.update({
  id: '/ajuda/$slug',
  path: '/ajuda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCarrinhoRoute = CheckoutCarrinhoRouteImport.update({
  id: '/checkout/carrinho',
  path: '/checkout/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutLoginRoute = CheckoutLoginRouteImport.update({
  id: '/checkout/login',
  path: '/checkout/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPedidoRoute = CheckoutPedidoRouteImport.update({
  id: '/checkout/pedido',
  path: '/checkout/pedido',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/$slug/p': typeof SlugPRoute
  '/ajuda/$slug': typeof AjudaSlugRoute
  '/checkout/carrinho': typeof CheckoutCarrinhoRoute
  '/checkout/login': typeof CheckoutLoginRoute
  '/checkout/pedido': typeof CheckoutPedidoRoute
  '/$slug/': typeof SlugIndexRoute
  '/ajuda/': typeof AjudaIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/$slug/p': typeof SlugPRoute
  '/ajuda/$slug': typeof AjudaSlugRoute
  '/checkout/carrinho': typeof CheckoutCarrinhoRoute
  '/checkout/login': typeof CheckoutLoginRoute
  '/checkout/pedido': typeof CheckoutPedidoRoute
  '/$slug': typeof SlugIndexRoute
  '/ajuda': typeof AjudaIndexRoute
  '/checkout': typeof CheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/$slug/p': typeof SlugPRoute
  '/ajuda/$slug': typeof AjudaSlugRoute
  '/checkout/carrinho': typeof CheckoutCarrinhoRoute
  '/checkout/login': typeof CheckoutLoginRoute
  '/checkout/pedido': typeof CheckoutPedidoRoute
  '/$slug/': typeof SlugIndexRoute
  '/ajuda/': typeof AjudaIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/$slug/p'
    | '/ajuda/$slug'
    | '/checkout/carrinho'
    | '/checkout/login'
    | '/checkout/pedido'
    | '/$slug/'
    | '/ajuda/'
    | '/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/$slug/p'
    | '/ajuda/$slug'
    | '/checkout/carrinho'
    | '/checkout/login'
    | '/checkout/pedido'
    | '/$slug'
    | '/ajuda'
    | '/checkout'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/$slug/p'
    | '/ajuda/$slug'
    | '/checkout/carrinho'
    | '/checkout/login'
    | '/checkout/pedido'
    | '/$slug/'
    | '/ajuda/'
    | '/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  SlugPRoute: typeof SlugPRoute
  AjudaSlugRoute: typeof AjudaSlugRoute
  CheckoutCarrinhoRoute: typeof CheckoutCarrinhoRoute
  CheckoutLoginRoute: typeof CheckoutLoginRoute
  CheckoutPedidoRoute: typeof CheckoutPedidoRoute
  SlugIndexRoute: typeof SlugIndexRoute
  AjudaIndexRoute: typeof AjudaIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/p': {
      id: '/$slug/p'
      path: '/$slug/p'
      fullPath: '/$slug/p'
      preLoaderRoute: typeof SlugPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda/': {
      id: '/ajuda/'
      path: '/ajuda'
      fullPath: '/ajuda/'
      preLoaderRoute: typeof AjudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda/$slug': {
      id: '/ajuda/$slug'
      path: '/ajuda/$slug'
      fullPath: '/ajuda/$slug'
      preLoaderRoute: typeof AjudaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/carrinho': {
      id: '/checkout/carrinho'
      path: '/checkout/carrinho'
      fullPath: '/checkout/carrinho'
      preLoaderRoute: typeof CheckoutCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/login': {
      id: '/checkout/login'
      path: '/checkout/login'
      fullPath: '/checkout/login'
      preLoaderRoute: typeof CheckoutLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pedido': {
      id: '/checkout/pedido'
      path: '/checkout/pedido'
      fullPath: '/checkout/pedido'
      preLoaderRoute: typeof CheckoutPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  SlugPRoute: SlugPRoute,
  AjudaSlugRoute: AjudaSlugRoute,
  CheckoutCarrinhoRoute: CheckoutCarrinhoRoute,
  CheckoutLoginRoute: CheckoutLoginRoute,
  CheckoutPedidoRoute: CheckoutPedidoRoute,
  SlugIndexRoute: SlugIndexRoute,
  AjudaIndexRoute: AjudaIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
