/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugPRouteImport } from './routes/$slug/p'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AjudaIndexRouteImport } from './routes/ajuda.index'
import { Route as AjudaSlugRouteImport } from './routes/ajuda.$slug'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutCarrinhoRouteImport } from './routes/checkout/carrinho'
import { Route as CheckoutLoginRouteImport } from './routes/checkout/login'
import { Route as CheckoutPedidoRouteImport } from './routes/checkout/pedido'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin/clientes'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin/cupons'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugPRoute = SlugPRouteImport.update({
  id: '/$slug/p',
  path: '/$slug/p',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AjudaIndexRoute = AjudaIndexRouteImport.update({
  id: '/ajuda/',
  path: '/ajuda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaSlugRoute = AjudaSlugRouteImport.update({
  id: '/ajuda/$slug',
  path: '/ajuda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCarrinhoRoute = CheckoutCarrinhoRouteImport.update({
  id: '/checkout/carrinho',
  path: '/checkout/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutLoginRoute = CheckoutLoginRouteImport.update({
  id: '/checkout/login',
  path: '/checkout/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPedidoRoute = CheckoutPedidoRouteImport.update({
  id: '/checkout/pedido',
  path: '/checkout/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/$slug/p': typeof SlugPRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ajuda/$slug': typeof AjudaSlugRoute
  '/checkout/carrinho': typeof CheckoutCarrinhoRoute
  '/checkout/login': typeof CheckoutLoginRoute
  '/checkout/pedido': typeof CheckoutPedidoRoute
  '/$slug/': typeof SlugIndexRoute
  '/ajuda/': typeof AjudaIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/$slug/p': typeof SlugPRoute
  '/ajuda/$slug': typeof AjudaSlugRoute
  '/checkout/carrinho': typeof CheckoutCarrinhoRoute
  '/checkout/login': typeof CheckoutLoginRoute
  '/checkout/pedido': typeof CheckoutPedidoRoute
  '/$slug': typeof SlugIndexRoute
  '/ajuda': typeof AjudaIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/$slug/p': typeof SlugPRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ajuda/$slug': typeof AjudaSlugRoute
  '/checkout/carrinho': typeof CheckoutCarrinhoRoute
  '/checkout/login': typeof CheckoutLoginRoute
  '/checkout/pedido': typeof CheckoutPedidoRoute
  '/$slug/': typeof SlugIndexRoute
  '/ajuda/': typeof AjudaIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/$slug/p'
    | '/admin'
    | '/ajuda/$slug'
    | '/checkout/carrinho'
    | '/checkout/login'
    | '/checkout/pedido'
    | '/$slug/'
    | '/ajuda/'
    | '/checkout/'
    | '/admin/clientes'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/$slug/p'
    | '/ajuda/$slug'
    | '/checkout/carrinho'
    | '/checkout/login'
    | '/checkout/pedido'
    | '/$slug'
    | '/ajuda'
    | '/checkout'
    | '/admin/clientes'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/busca'
    | '/$slug/p'
    | '/_authenticated/admin'
    | '/ajuda/$slug'
    | '/checkout/carrinho'
    | '/checkout/login'
    | '/checkout/pedido'
    | '/$slug/'
    | '/ajuda/'
    | '/checkout/'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  SlugPRoute: typeof SlugPRoute
  AjudaSlugRoute: typeof AjudaSlugRoute
  CheckoutCarrinhoRoute: typeof CheckoutCarrinhoRoute
  CheckoutLoginRoute: typeof CheckoutLoginRoute
  CheckoutPedidoRoute: typeof CheckoutPedidoRoute
  SlugIndexRoute: typeof SlugIndexRoute
  AjudaIndexRoute: typeof AjudaIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/p': {
      id: '/$slug/p'
      path: '/$slug/p'
      fullPath: '/$slug/p'
      preLoaderRoute: typeof SlugPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ajuda/': {
      id: '/ajuda/'
      path: '/ajuda'
      fullPath: '/ajuda/'
      preLoaderRoute: typeof AjudaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda/$slug': {
      id: '/ajuda/$slug'
      path: '/ajuda/$slug'
      fullPath: '/ajuda/$slug'
      preLoaderRoute: typeof AjudaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/carrinho': {
      id: '/checkout/carrinho'
      path: '/checkout/carrinho'
      fullPath: '/checkout/carrinho'
      preLoaderRoute: typeof CheckoutCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/login': {
      id: '/checkout/login'
      path: '/checkout/login'
      fullPath: '/checkout/login'
      preLoaderRoute: typeof CheckoutLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pedido': {
      id: '/checkout/pedido'
      path: '/checkout/pedido'
      fullPath: '/checkout/pedido'
      preLoaderRoute: typeof CheckoutPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  SlugPRoute: SlugPRoute,
  AjudaSlugRoute: AjudaSlugRoute,
  CheckoutCarrinhoRoute: CheckoutCarrinhoRoute,
  CheckoutLoginRoute: CheckoutLoginRoute,
  CheckoutPedidoRoute: CheckoutPedidoRoute,
  SlugIndexRoute: SlugIndexRoute,
  AjudaIndexRoute: AjudaIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
